-- Single migration: Washington incorporated cities/towns (281) plus Seattle neighborhoods and
-- common colloquial labels. App matches user input on save; not every CDP/unincorporated place is listed.

-- Tear down legacy objects if a DB was created from older migrations.
DROP TRIGGER IF EXISTS photos_normalize_neighborhood_trigger ON public.photos;
DROP FUNCTION IF EXISTS public.photos_normalize_neighborhood();
DROP FUNCTION IF EXISTS public.normalize_neighborhood_case(text);
DROP FUNCTION IF EXISTS public.get_browse_neighborhoods(uuid);
ALTER TABLE public.photos DROP COLUMN IF EXISTS neighborhood_raw;

CREATE TABLE IF NOT EXISTS public.neighborhood_canonicals (
  label text PRIMARY KEY
);

COMMENT ON TABLE public.neighborhood_canonicals IS
  'Location labels for autocomplete and save-time normalization: all WA cities/towns; Seattle neighborhoods; Puget Sound colloquial names.';

INSERT INTO public.neighborhood_canonicals (label) VALUES
  ('Aberdeen'),
  ('Adams'),
  ('Airway Heights'),
  ('Albion'),
  ('Algona'),
  ('Alki Point'),
  ('Almira'),
  ('Anacortes'),
  ('Arbor Heights'),
  ('Arlington'),
  ('Asotin'),
  ('Atlantic'),
  ('Auburn'),
  ('Bainbridge Island'),
  ('Ballard'),
  ('Battle Ground'),
  ('Beacon Hill'),
  ('Beaux Arts Village'),
  ('Bellevue'),
  ('Bellingham'),
  ('Belltown'),
  ('Benton City'),
  ('Bingen'),
  ('Bitter Lake'),
  ('Black Diamond'),
  ('Blaine'),
  ('Blue Ridge'),
  ('Bonney Lake'),
  ('Bothell'),
  ('Bremerton'),
  ('Brewster'),
  ('Briarcliff'),
  ('Bridgeport'),
  ('Brier'),
  ('Brighton'),
  ('Broadmoor'),
  ('Broadview'),
  ('Broadway'),
  ('Bryant'),
  ('Buckley'),
  ('Bucoda'),
  ('Burien'),
  ('Burlington'),
  ('Camas'),
  ('Capitol Hill'),
  ('Carbonado'),
  ('Carnation'),
  ('Cascade'),
  ('Cashmere'),
  ('Castle Rock'),
  ('Cathlamet'),
  ('Cedar Park'),
  ('Central Business District'),
  ('Central District'),
  ('Central Waterfront'),
  ('Centralia'),
  ('Chehalis'),
  ('Chelan'),
  ('Cheney'),
  ('Cherry Hill'),
  ('Chewelah'),
  ('Chinatown-International District'),
  ('Clarkston'),
  ('Cle Elum'),
  ('Clyde Hill'),
  ('Colfax'),
  ('College Place'),
  ('Colton'),
  ('Columbia City'),
  ('Colville'),
  ('Conconully'),
  ('Concrete'),
  ('Connell'),
  ('Cosmopolis'),
  ('Coulee City'),
  ('Coulee Dam'),
  ('Coupeville'),
  ('Covington'),
  ('Creston'),
  ('Crown Hill'),
  ('Cusick'),
  ('Darrington'),
  ('Davenport'),
  ('Dayton'),
  ('Deer Park'),
  ('Delridge'),
  ('Denny Regrade'),
  ('Denny Triangle'),
  ('Denny-Blaine'),
  ('Des Moines'),
  ('Downtown'),
  ('Dunlap'),
  ('DuPont'),
  ('Duvall'),
  ('East Queen Anne'),
  ('East Wenatchee'),
  ('Eastlake'),
  ('Eatonville'),
  ('Edgewood'),
  ('Edmonds'),
  ('Electric City'),
  ('Ellensburg'),
  ('Elma'),
  ('Elmer City'),
  ('Endicott'),
  ('Entiat'),
  ('Enumclaw'),
  ('Ephrata'),
  ('Everett'),
  ('Everson'),
  ('Fairfield'),
  ('Fairmount Park'),
  ('Fall City'),
  ('Farmington'),
  ('Fauntleroy'),
  ('Federal Way'),
  ('Ferndale'),
  ('Fife'),
  ('Fircrest'),
  ('First Hill'),
  ('Forks'),
  ('Frelard'),
  ('Fremont'),
  ('Friday Harbor'),
  ('Garfield'),
  ('Garfield High School'),
  ('Gatewood'),
  ('Genesee'),
  ('George'),
  ('Georgetown'),
  ('Gig Harbor'),
  ('Gold Bar'),
  ('Goldendale'),
  ('Grand Coulee'),
  ('Grandview'),
  ('Granger'),
  ('Granite Falls'),
  ('Green Lake'),
  ('Greenwood'),
  ('Haller Lake'),
  ('Hamilton'),
  ('Harbor Island'),
  ('Harrah'),
  ('Harrington'),
  ('Hartline'),
  ('Hatton'),
  ('Hawthorne Hills'),
  ('High Point'),
  ('Highland Park'),
  ('Hillman City'),
  ('Hoquiam'),
  ('Hunts Point'),
  ('Ilwaco'),
  ('Index'),
  ('Industrial District'),
  ('Interbay'),
  ('International District'),
  ('Ione'),
  ('Issaquah'),
  ('Judkins Park'),
  ('Junction'),
  ('Kahlotus'),
  ('Kalama'),
  ('Kelso'),
  ('Kenmore'),
  ('Kennewick'),
  ('Kent'),
  ('Kettle Falls'),
  ('Kirkland'),
  ('Kittitas'),
  ('Krupp'),
  ('La Center'),
  ('La Conner'),
  ('Lacey'),
  ('LaCrosse'),
  ('Lake City'),
  ('Lake Forest Park'),
  ('Lake Stevens'),
  ('Lakewood'),
  ('Lamont'),
  ('Langley'),
  ('Latah'),
  ('Laurelhurst'),
  ('Lawton Park'),
  ('Leavenworth'),
  ('Leschi'),
  ('Liberty Lake'),
  ('Licton Springs'),
  ('Lind'),
  ('Long Beach'),
  ('Longview'),
  ('Lower Queen Anne'),
  ('Loyal Heights'),
  ('Lyman'),
  ('Lynden'),
  ('Lynnwood'),
  ('Mabton'),
  ('Madison Park'),
  ('Madison Valley'),
  ('Madrona'),
  ('Madrona Valley'),
  ('Magnolia'),
  ('Malden'),
  ('Mann'),
  ('Mansfield'),
  ('Maple Leaf'),
  ('Maple Valley'),
  ('Marcus'),
  ('Marysville'),
  ('Mattawa'),
  ('Matthews Beach'),
  ('Maury Island'),
  ('McCleary'),
  ('Meadowbrook'),
  ('Medical Lake'),
  ('Medina'),
  ('Mercer Island'),
  ('Meridian'),
  ('Mesa'),
  ('Metaline'),
  ('Metaline Falls'),
  ('Mill Creek'),
  ('Millwood'),
  ('Milton'),
  ('Minor'),
  ('Monroe'),
  ('Montesano'),
  ('Montlake'),
  ('Morton'),
  ('Moses Lake'),
  ('Mossyrock'),
  ('Mount Baker'),
  ('Mount Vernon'),
  ('Mountlake Terrace'),
  ('Moxee'),
  ('Mukilteo'),
  ('Naches'),
  ('Napavine'),
  ('Nespelem'),
  ('Newcastle'),
  ('NewHolly'),
  ('Newport'),
  ('Nooksack'),
  ('Normandy Park'),
  ('North Admiral'),
  ('North Beach'),
  ('North Beacon Hill'),
  ('North Bend'),
  ('North Bonneville'),
  ('North Delridge'),
  ('North Queen Anne'),
  ('Northgate'),
  ('Northlake'),
  ('Northport'),
  ('Oak Harbor'),
  ('Oakesdale'),
  ('Oakville'),
  ('Ocean Shores'),
  ('Odessa'),
  ('Okanogan'),
  ('Olympia'),
  ('Olympic Hills'),
  ('Omak'),
  ('Oroville'),
  ('Orting'),
  ('Othello'),
  ('Pacific'),
  ('Palouse'),
  ('Pasco'),
  ('Pateros'),
  ('Pe Ell'),
  ('Phinney Ridge'),
  ('Pigeon Point'),
  ('Pike Place Market'),
  ('Pike-Pine Corridor'),
  ('Pinehurst'),
  ('Pioneer Square'),
  ('Pomeroy'),
  ('Port Angeles'),
  ('Port Orchard'),
  ('Port Townsend'),
  ('Poulsbo'),
  ('Prescott'),
  ('Preston'),
  ('Prosser'),
  ('Pullman'),
  ('Puyallup'),
  ('Queen Anne'),
  ('Quincy'),
  ('Rainier'),
  ('Rainier Beach'),
  ('Rainier Valley'),
  ('Rainier View'),
  ('Ravenna'),
  ('Raymond'),
  ('Reardan'),
  ('Redmond'),
  ('Renton'),
  ('Renton Hill'),
  ('Republic'),
  ('Richland'),
  ('Ridgefield'),
  ('Ritzville'),
  ('Riverside'),
  ('Riverview'),
  ('Roanoke'),
  ('Roanoke Park Historic District'),
  ('Rock Island'),
  ('Rockford'),
  ('Roosevelt'),
  ('Rosalia'),
  ('Roslyn'),
  ('Roxhill'),
  ('Roy'),
  ('Royal City'),
  ('Ruston'),
  ('Sammamish'),
  ('Sand Point'),
  ('SeaTac'),
  ('Seattle'),
  ('Seattle Hebrew Academy'),
  ('Seattle Landmarks'),
  ('Seattle Post-Intelligencer'),
  ('Seattle Public Library'),
  ('Seaview'),
  ('Sedro-Woolley'),
  ('Selah'),
  ('Sequim'),
  ('Seward Park'),
  ('Shelton'),
  ('Shoreline'),
  ('Skykomish'),
  ('SLU'),
  ('Snohomish'),
  ('Snoqualmie'),
  ('Soap Lake'),
  ('SoDo'),
  ('South Beacon Hill'),
  ('South Bend'),
  ('South Cle Elum'),
  ('South Delridge'),
  ('South End'),
  ('South Lake Union'),
  ('South Park'),
  ('South Prairie'),
  ('South Seattle'),
  ('Southeast Magnolia'),
  ('Southeast Seattle'),
  ('Spangle'),
  ('Spokane'),
  ('Spokane Valley'),
  ('Sprague'),
  ('Springdale'),
  ('Squire Park'),
  ('St. John'),
  ('Stanwood'),
  ('Starbuck'),
  ('Steilacoom'),
  ('Stevens'),
  ('Stevenson'),
  ('Street layout of Seattle'),
  ('Sultan'),
  ('Sumas'),
  ('Sumner'),
  ('Sunnyside'),
  ('Sunset Hill'),
  ('Tacoma'),
  ('Tekoa'),
  ('Tenino'),
  ('Tieton'),
  ('Toledo'),
  ('Tonasket'),
  ('Toppenish'),
  ('Tukwila'),
  ('Tumwater'),
  ('Twisp'),
  ('U District'),
  ('Union Gap'),
  ('Uniontown'),
  ('University District'),
  ('University Place'),
  ('University Village'),
  ('Vader'),
  ('Vancouver'),
  ('Vashon'),
  ('Victory Heights'),
  ('View Ridge'),
  ('Waitsburg'),
  ('Walla Walla'),
  ('Wallingford'),
  ('Wapato'),
  ('Warden'),
  ('Washington Park'),
  ('Washougal'),
  ('Washtucna'),
  ('Waterville'),
  ('Waverly'),
  ('Wedgwood'),
  ('Wenatchee'),
  ('West Edge'),
  ('West Queen Anne'),
  ('West Richland'),
  ('West Seattle'),
  ('West Seattle Junction'),
  ('West Woodland'),
  ('Westlake'),
  ('Westlake Seattle'),
  ('Westport'),
  ('White Center'),
  ('White Salmon'),
  ('Whittier Heights'),
  ('Wilbur'),
  ('Wilkeson'),
  ('Wilson Creek'),
  ('Windermere'),
  ('Winlock'),
  ('Winthrop'),
  ('Woodinville'),
  ('Woodland'),
  ('Woodway'),
  ('Yacolt'),
  ('Yakima'),
  ('Yarrow Point'),
  ('Yelm'),
  ('Yesler Terrace'),
  ('Zillah')
ON CONFLICT (label) DO NOTHING;

ALTER TABLE public.neighborhood_canonicals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "neighborhood_canonicals_select_authenticated" ON public.neighborhood_canonicals;
CREATE POLICY "neighborhood_canonicals_select_authenticated"
  ON public.neighborhood_canonicals FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "neighborhood_canonicals_select_anon" ON public.neighborhood_canonicals;
CREATE POLICY "neighborhood_canonicals_select_anon"
  ON public.neighborhood_canonicals FOR SELECT
  TO anon
  USING (true);

GRANT SELECT ON public.neighborhood_canonicals TO authenticated;
GRANT SELECT ON public.neighborhood_canonicals TO anon;

CREATE OR REPLACE FUNCTION public.photos_fts_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.fts := to_tsvector(
    'english',
    coalesce(NEW.title, '') || ' ' ||
    coalesce(NEW.neighborhood, '') || ' ' ||
    coalesce(NEW.description, '') || ' ' ||
    coalesce(array_to_string(NEW.tags, ' '), '')
  );
  RETURN NEW;
END;
$$;

UPDATE public.photos SET title = title;
